<a href="https://colab.research.google.com/github/Yash19934/pytorch_tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bidict                           0.23.1

In [2]:
##Lists
my_lists = [[1,2,3,4],[5,6,7,2],[4,3,2,1]]
my_lists

[[1, 2, 3, 4], [5, 6, 7, 2], [4, 3, 2, 1]]

In [8]:
##numpy array

np_rand = np.random.rand(3,4)

In [10]:
##tensor
tensor_random = torch.randn(3,4)
tensor_random


tensor([[ 1.3786,  0.3039, -0.7174,  0.0758],
        [ 0.9716,  0.0148,  0.4881,  0.0325],
        [-0.6481, -1.4065, -0.4307, -0.4285]])

In [11]:
tensor_random.dtype

torch.float32

In [14]:
torch.tensor(np_rand)

tensor([[0.2073, 0.9678, 0.8412, 0.4529],
        [0.6604, 0.3728, 0.8840, 0.6511],
        [0.4848, 0.9735, 0.5346, 0.8150]], dtype=torch.float64)

In [16]:
torch.tensor(my_lists).dtype

torch.int64

In [19]:
torch.zeros(1,2,3,4)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [20]:
my_torch = torch.arange(10)

In [28]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#Reshape and View
my_torch.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
my_torch.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [34]:
my_torch.reshape(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [36]:
my_torch.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [47]:
torch_2 = torch.arange(0,10)
torch_2 = torch_2.reshape(5,2)

In [50]:
torch_2[3:,0]

tensor([6, 8])

In [66]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([[4,5,6,8]])

In [65]:
tensor_a + tensor_b

tensor([[ 5,  7,  9, 12],
        [ 2,  3,  4,  5]])

In [61]:
torch.add(tensor_a,tensor_b)

tensor([[ 5,  7,  9, 12],
        [ 9, 11, 13, 16]])

In [62]:
torch.subtract(tensor_a,tensor_b)

tensor([[-3, -3, -3, -4],
        [ 1,  1,  1,  0]])

In [67]:
tensor_a * tensor_b

tensor([[ 4, 10, 18, 32]])

In [68]:
tensor_a / tensor_b

tensor([[0.2500, 0.4000, 0.5000, 0.5000]])

In [69]:
tensor_b % tensor_a

tensor([[0, 1, 0, 0]])

In [70]:
torch.pow(tensor_b, tensor_a)

tensor([[   4,   25,  216, 4096]])